//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eBizChargeForSAP.B1InstallService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SAPError", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SAPError : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RecIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        private System.Nullable<System.DateTime> recDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RecID {
            get {
                return this.RecIDField;
            }
            set {
                if ((this.RecIDField.Equals(value) != true)) {
                    this.RecIDField = value;
                    this.RaisePropertyChanged("RecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> recDate {
            get {
                return this.recDateField;
            }
            set {
                if ((this.recDateField.Equals(value) != true)) {
                    this.recDateField = value;
                    this.RaisePropertyChanged("recDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DBName {
            get {
                return this.DBNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DBNameField, value) != true)) {
                    this.DBNameField = value;
                    this.RaisePropertyChanged("DBName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string AppUser {
            get {
                return this.AppUserField;
            }
            set {
                if ((object.ReferenceEquals(this.AppUserField, value) != true)) {
                    this.AppUserField = value;
                    this.RaisePropertyChanged("AppUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SAPB1Install", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SAPB1Install : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RecIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DomainField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubnetMaskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SourceKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseServerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppPassWDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBPassWDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sandboxField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int RecID {
            get {
                return this.RecIDField;
            }
            set {
                if ((this.RecIDField.Equals(value) != true)) {
                    this.RecIDField = value;
                    this.RaisePropertyChanged("RecID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Domain {
            get {
                return this.DomainField;
            }
            set {
                if ((object.ReferenceEquals(this.DomainField, value) != true)) {
                    this.DomainField = value;
                    this.RaisePropertyChanged("Domain");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IP {
            get {
                return this.IPField;
            }
            set {
                if ((object.ReferenceEquals(this.IPField, value) != true)) {
                    this.IPField = value;
                    this.RaisePropertyChanged("IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SubnetMask {
            get {
                return this.SubnetMaskField;
            }
            set {
                if ((object.ReferenceEquals(this.SubnetMaskField, value) != true)) {
                    this.SubnetMaskField = value;
                    this.RaisePropertyChanged("SubnetMask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SourceKey {
            get {
                return this.SourceKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SourceKeyField, value) != true)) {
                    this.SourceKeyField = value;
                    this.RaisePropertyChanged("SourceKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PIN {
            get {
                return this.PINField;
            }
            set {
                if ((object.ReferenceEquals(this.PINField, value) != true)) {
                    this.PINField = value;
                    this.RaisePropertyChanged("PIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string DBServer {
            get {
                return this.DBServerField;
            }
            set {
                if ((object.ReferenceEquals(this.DBServerField, value) != true)) {
                    this.DBServerField = value;
                    this.RaisePropertyChanged("DBServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string LicenseServer {
            get {
                return this.LicenseServerField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseServerField, value) != true)) {
                    this.LicenseServerField = value;
                    this.RaisePropertyChanged("LicenseServer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string AppUser {
            get {
                return this.AppUserField;
            }
            set {
                if ((object.ReferenceEquals(this.AppUserField, value) != true)) {
                    this.AppUserField = value;
                    this.RaisePropertyChanged("AppUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string AppPassWD {
            get {
                return this.AppPassWDField;
            }
            set {
                if ((object.ReferenceEquals(this.AppPassWDField, value) != true)) {
                    this.AppPassWDField = value;
                    this.RaisePropertyChanged("AppPassWD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string DBUser {
            get {
                return this.DBUserField;
            }
            set {
                if ((object.ReferenceEquals(this.DBUserField, value) != true)) {
                    this.DBUserField = value;
                    this.RaisePropertyChanged("DBUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string DBPassWD {
            get {
                return this.DBPassWDField;
            }
            set {
                if ((object.ReferenceEquals(this.DBPassWDField, value) != true)) {
                    this.DBPassWDField = value;
                    this.RaisePropertyChanged("DBPassWD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string DBName {
            get {
                return this.DBNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DBNameField, value) != true)) {
                    this.DBNameField = value;
                    this.RaisePropertyChanged("DBName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string DBType {
            get {
                return this.DBTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DBTypeField, value) != true)) {
                    this.DBTypeField = value;
                    this.RaisePropertyChanged("DBType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string sandbox {
            get {
                return this.sandboxField;
            }
            set {
                if ((object.ReferenceEquals(this.sandboxField, value) != true)) {
                    this.sandboxField = value;
                    this.RaisePropertyChanged("sandbox");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="B1InstallService.B1InstallServiceSoap")]
    public interface B1InstallServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        eBizChargeForSAP.B1InstallService.HelloWorldResponse HelloWorld(eBizChargeForSAP.B1InstallService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.HelloWorldResponse> HelloWorldAsync(eBizChargeForSAP.B1InstallService.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name err from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogError", ReplyAction="*")]
        eBizChargeForSAP.B1InstallService.LogErrorResponse LogError(eBizChargeForSAP.B1InstallService.LogErrorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogError", ReplyAction="*")]
        System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.LogErrorResponse> LogErrorAsync(eBizChargeForSAP.B1InstallService.LogErrorRequest request);
        
        // CODEGEN: Generating message contract since element name b1info from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpsertInfo", ReplyAction="*")]
        eBizChargeForSAP.B1InstallService.UpsertInfoResponse UpsertInfo(eBizChargeForSAP.B1InstallService.UpsertInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpsertInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.UpsertInfoResponse> UpsertInfoAsync(eBizChargeForSAP.B1InstallService.UpsertInfoRequest request);
        
        // CODEGEN: Generating message contract since element name licenseServer from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoByLicSvr", ReplyAction="*")]
        eBizChargeForSAP.B1InstallService.GetInfoByLicSvrResponse GetInfoByLicSvr(eBizChargeForSAP.B1InstallService.GetInfoByLicSvrRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoByLicSvr", ReplyAction="*")]
        System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.GetInfoByLicSvrResponse> GetInfoByLicSvrAsync(eBizChargeForSAP.B1InstallService.GetInfoByLicSvrRequest request);
        
        // CODEGEN: Generating message contract since element name domain from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoByDomain", ReplyAction="*")]
        eBizChargeForSAP.B1InstallService.GetInfoByDomainResponse GetInfoByDomain(eBizChargeForSAP.B1InstallService.GetInfoByDomainRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInfoByDomain", ReplyAction="*")]
        System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.GetInfoByDomainResponse> GetInfoByDomainAsync(eBizChargeForSAP.B1InstallService.GetInfoByDomainRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public eBizChargeForSAP.B1InstallService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(eBizChargeForSAP.B1InstallService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public eBizChargeForSAP.B1InstallService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(eBizChargeForSAP.B1InstallService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogErrorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogError", Namespace="http://tempuri.org/", Order=0)]
        public eBizChargeForSAP.B1InstallService.LogErrorRequestBody Body;
        
        public LogErrorRequest() {
        }
        
        public LogErrorRequest(eBizChargeForSAP.B1InstallService.LogErrorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogErrorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eBizChargeForSAP.B1InstallService.SAPError err;
        
        public LogErrorRequestBody() {
        }
        
        public LogErrorRequestBody(eBizChargeForSAP.B1InstallService.SAPError err) {
            this.err = err;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogErrorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogErrorResponse", Namespace="http://tempuri.org/", Order=0)]
        public eBizChargeForSAP.B1InstallService.LogErrorResponseBody Body;
        
        public LogErrorResponse() {
        }
        
        public LogErrorResponse(eBizChargeForSAP.B1InstallService.LogErrorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LogErrorResponseBody {
        
        public LogErrorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpsertInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpsertInfo", Namespace="http://tempuri.org/", Order=0)]
        public eBizChargeForSAP.B1InstallService.UpsertInfoRequestBody Body;
        
        public UpsertInfoRequest() {
        }
        
        public UpsertInfoRequest(eBizChargeForSAP.B1InstallService.UpsertInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpsertInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eBizChargeForSAP.B1InstallService.SAPB1Install b1info;
        
        public UpsertInfoRequestBody() {
        }
        
        public UpsertInfoRequestBody(eBizChargeForSAP.B1InstallService.SAPB1Install b1info) {
            this.b1info = b1info;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpsertInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpsertInfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public eBizChargeForSAP.B1InstallService.UpsertInfoResponseBody Body;
        
        public UpsertInfoResponse() {
        }
        
        public UpsertInfoResponse(eBizChargeForSAP.B1InstallService.UpsertInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpsertInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpsertInfoResult;
        
        public UpsertInfoResponseBody() {
        }
        
        public UpsertInfoResponseBody(string UpsertInfoResult) {
            this.UpsertInfoResult = UpsertInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoByLicSvrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoByLicSvr", Namespace="http://tempuri.org/", Order=0)]
        public eBizChargeForSAP.B1InstallService.GetInfoByLicSvrRequestBody Body;
        
        public GetInfoByLicSvrRequest() {
        }
        
        public GetInfoByLicSvrRequest(eBizChargeForSAP.B1InstallService.GetInfoByLicSvrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoByLicSvrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string licenseServer;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string domain;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string dbname;
        
        public GetInfoByLicSvrRequestBody() {
        }
        
        public GetInfoByLicSvrRequestBody(string licenseServer, string domain, string dbname) {
            this.licenseServer = licenseServer;
            this.domain = domain;
            this.dbname = dbname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoByLicSvrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoByLicSvrResponse", Namespace="http://tempuri.org/", Order=0)]
        public eBizChargeForSAP.B1InstallService.GetInfoByLicSvrResponseBody Body;
        
        public GetInfoByLicSvrResponse() {
        }
        
        public GetInfoByLicSvrResponse(eBizChargeForSAP.B1InstallService.GetInfoByLicSvrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoByLicSvrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eBizChargeForSAP.B1InstallService.SAPB1Install GetInfoByLicSvrResult;
        
        public GetInfoByLicSvrResponseBody() {
        }
        
        public GetInfoByLicSvrResponseBody(eBizChargeForSAP.B1InstallService.SAPB1Install GetInfoByLicSvrResult) {
            this.GetInfoByLicSvrResult = GetInfoByLicSvrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoByDomainRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoByDomain", Namespace="http://tempuri.org/", Order=0)]
        public eBizChargeForSAP.B1InstallService.GetInfoByDomainRequestBody Body;
        
        public GetInfoByDomainRequest() {
        }
        
        public GetInfoByDomainRequest(eBizChargeForSAP.B1InstallService.GetInfoByDomainRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoByDomainRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string domain;
        
        public GetInfoByDomainRequestBody() {
        }
        
        public GetInfoByDomainRequestBody(string domain) {
            this.domain = domain;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInfoByDomainResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInfoByDomainResponse", Namespace="http://tempuri.org/", Order=0)]
        public eBizChargeForSAP.B1InstallService.GetInfoByDomainResponseBody Body;
        
        public GetInfoByDomainResponse() {
        }
        
        public GetInfoByDomainResponse(eBizChargeForSAP.B1InstallService.GetInfoByDomainResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetInfoByDomainResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public eBizChargeForSAP.B1InstallService.SAPB1Install GetInfoByDomainResult;
        
        public GetInfoByDomainResponseBody() {
        }
        
        public GetInfoByDomainResponseBody(eBizChargeForSAP.B1InstallService.SAPB1Install GetInfoByDomainResult) {
            this.GetInfoByDomainResult = GetInfoByDomainResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface B1InstallServiceSoapChannel : eBizChargeForSAP.B1InstallService.B1InstallServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class B1InstallServiceSoapClient : System.ServiceModel.ClientBase<eBizChargeForSAP.B1InstallService.B1InstallServiceSoap>, eBizChargeForSAP.B1InstallService.B1InstallServiceSoap {
        
        public B1InstallServiceSoapClient() {
        }
        
        public B1InstallServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public B1InstallServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B1InstallServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public B1InstallServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBizChargeForSAP.B1InstallService.HelloWorldResponse eBizChargeForSAP.B1InstallService.B1InstallServiceSoap.HelloWorld(eBizChargeForSAP.B1InstallService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            eBizChargeForSAP.B1InstallService.HelloWorldRequest inValue = new eBizChargeForSAP.B1InstallService.HelloWorldRequest();
            inValue.Body = new eBizChargeForSAP.B1InstallService.HelloWorldRequestBody();
            eBizChargeForSAP.B1InstallService.HelloWorldResponse retVal = ((eBizChargeForSAP.B1InstallService.B1InstallServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.HelloWorldResponse> eBizChargeForSAP.B1InstallService.B1InstallServiceSoap.HelloWorldAsync(eBizChargeForSAP.B1InstallService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.HelloWorldResponse> HelloWorldAsync() {
            eBizChargeForSAP.B1InstallService.HelloWorldRequest inValue = new eBizChargeForSAP.B1InstallService.HelloWorldRequest();
            inValue.Body = new eBizChargeForSAP.B1InstallService.HelloWorldRequestBody();
            return ((eBizChargeForSAP.B1InstallService.B1InstallServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBizChargeForSAP.B1InstallService.LogErrorResponse eBizChargeForSAP.B1InstallService.B1InstallServiceSoap.LogError(eBizChargeForSAP.B1InstallService.LogErrorRequest request) {
            return base.Channel.LogError(request);
        }
        
        public void LogError(eBizChargeForSAP.B1InstallService.SAPError err) {
            eBizChargeForSAP.B1InstallService.LogErrorRequest inValue = new eBizChargeForSAP.B1InstallService.LogErrorRequest();
            inValue.Body = new eBizChargeForSAP.B1InstallService.LogErrorRequestBody();
            inValue.Body.err = err;
            eBizChargeForSAP.B1InstallService.LogErrorResponse retVal = ((eBizChargeForSAP.B1InstallService.B1InstallServiceSoap)(this)).LogError(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.LogErrorResponse> eBizChargeForSAP.B1InstallService.B1InstallServiceSoap.LogErrorAsync(eBizChargeForSAP.B1InstallService.LogErrorRequest request) {
            return base.Channel.LogErrorAsync(request);
        }
        
        public System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.LogErrorResponse> LogErrorAsync(eBizChargeForSAP.B1InstallService.SAPError err) {
            eBizChargeForSAP.B1InstallService.LogErrorRequest inValue = new eBizChargeForSAP.B1InstallService.LogErrorRequest();
            inValue.Body = new eBizChargeForSAP.B1InstallService.LogErrorRequestBody();
            inValue.Body.err = err;
            return ((eBizChargeForSAP.B1InstallService.B1InstallServiceSoap)(this)).LogErrorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBizChargeForSAP.B1InstallService.UpsertInfoResponse eBizChargeForSAP.B1InstallService.B1InstallServiceSoap.UpsertInfo(eBizChargeForSAP.B1InstallService.UpsertInfoRequest request) {
            return base.Channel.UpsertInfo(request);
        }
        
        public string UpsertInfo(eBizChargeForSAP.B1InstallService.SAPB1Install b1info) {
            eBizChargeForSAP.B1InstallService.UpsertInfoRequest inValue = new eBizChargeForSAP.B1InstallService.UpsertInfoRequest();
            inValue.Body = new eBizChargeForSAP.B1InstallService.UpsertInfoRequestBody();
            inValue.Body.b1info = b1info;
            eBizChargeForSAP.B1InstallService.UpsertInfoResponse retVal = ((eBizChargeForSAP.B1InstallService.B1InstallServiceSoap)(this)).UpsertInfo(inValue);
            return retVal.Body.UpsertInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.UpsertInfoResponse> eBizChargeForSAP.B1InstallService.B1InstallServiceSoap.UpsertInfoAsync(eBizChargeForSAP.B1InstallService.UpsertInfoRequest request) {
            return base.Channel.UpsertInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.UpsertInfoResponse> UpsertInfoAsync(eBizChargeForSAP.B1InstallService.SAPB1Install b1info) {
            eBizChargeForSAP.B1InstallService.UpsertInfoRequest inValue = new eBizChargeForSAP.B1InstallService.UpsertInfoRequest();
            inValue.Body = new eBizChargeForSAP.B1InstallService.UpsertInfoRequestBody();
            inValue.Body.b1info = b1info;
            return ((eBizChargeForSAP.B1InstallService.B1InstallServiceSoap)(this)).UpsertInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBizChargeForSAP.B1InstallService.GetInfoByLicSvrResponse eBizChargeForSAP.B1InstallService.B1InstallServiceSoap.GetInfoByLicSvr(eBizChargeForSAP.B1InstallService.GetInfoByLicSvrRequest request) {
            return base.Channel.GetInfoByLicSvr(request);
        }
        
        public eBizChargeForSAP.B1InstallService.SAPB1Install GetInfoByLicSvr(string licenseServer, string domain, string dbname) {
            eBizChargeForSAP.B1InstallService.GetInfoByLicSvrRequest inValue = new eBizChargeForSAP.B1InstallService.GetInfoByLicSvrRequest();
            inValue.Body = new eBizChargeForSAP.B1InstallService.GetInfoByLicSvrRequestBody();
            inValue.Body.licenseServer = licenseServer;
            inValue.Body.domain = domain;
            inValue.Body.dbname = dbname;
            eBizChargeForSAP.B1InstallService.GetInfoByLicSvrResponse retVal = ((eBizChargeForSAP.B1InstallService.B1InstallServiceSoap)(this)).GetInfoByLicSvr(inValue);
            return retVal.Body.GetInfoByLicSvrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.GetInfoByLicSvrResponse> eBizChargeForSAP.B1InstallService.B1InstallServiceSoap.GetInfoByLicSvrAsync(eBizChargeForSAP.B1InstallService.GetInfoByLicSvrRequest request) {
            return base.Channel.GetInfoByLicSvrAsync(request);
        }
        
        public System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.GetInfoByLicSvrResponse> GetInfoByLicSvrAsync(string licenseServer, string domain, string dbname) {
            eBizChargeForSAP.B1InstallService.GetInfoByLicSvrRequest inValue = new eBizChargeForSAP.B1InstallService.GetInfoByLicSvrRequest();
            inValue.Body = new eBizChargeForSAP.B1InstallService.GetInfoByLicSvrRequestBody();
            inValue.Body.licenseServer = licenseServer;
            inValue.Body.domain = domain;
            inValue.Body.dbname = dbname;
            return ((eBizChargeForSAP.B1InstallService.B1InstallServiceSoap)(this)).GetInfoByLicSvrAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eBizChargeForSAP.B1InstallService.GetInfoByDomainResponse eBizChargeForSAP.B1InstallService.B1InstallServiceSoap.GetInfoByDomain(eBizChargeForSAP.B1InstallService.GetInfoByDomainRequest request) {
            return base.Channel.GetInfoByDomain(request);
        }
        
        public eBizChargeForSAP.B1InstallService.SAPB1Install GetInfoByDomain(string domain) {
            eBizChargeForSAP.B1InstallService.GetInfoByDomainRequest inValue = new eBizChargeForSAP.B1InstallService.GetInfoByDomainRequest();
            inValue.Body = new eBizChargeForSAP.B1InstallService.GetInfoByDomainRequestBody();
            inValue.Body.domain = domain;
            eBizChargeForSAP.B1InstallService.GetInfoByDomainResponse retVal = ((eBizChargeForSAP.B1InstallService.B1InstallServiceSoap)(this)).GetInfoByDomain(inValue);
            return retVal.Body.GetInfoByDomainResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.GetInfoByDomainResponse> eBizChargeForSAP.B1InstallService.B1InstallServiceSoap.GetInfoByDomainAsync(eBizChargeForSAP.B1InstallService.GetInfoByDomainRequest request) {
            return base.Channel.GetInfoByDomainAsync(request);
        }
        
        public System.Threading.Tasks.Task<eBizChargeForSAP.B1InstallService.GetInfoByDomainResponse> GetInfoByDomainAsync(string domain) {
            eBizChargeForSAP.B1InstallService.GetInfoByDomainRequest inValue = new eBizChargeForSAP.B1InstallService.GetInfoByDomainRequest();
            inValue.Body = new eBizChargeForSAP.B1InstallService.GetInfoByDomainRequestBody();
            inValue.Body.domain = domain;
            return ((eBizChargeForSAP.B1InstallService.B1InstallServiceSoap)(this)).GetInfoByDomainAsync(inValue);
        }
    }
}
